; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_zap
	.word @sfx_ntsc_boom
	.word @sfx_ntsc_bigboom

@sfx_ntsc_zap:
	.byte $81,$61,$82,$00,$80,$3f,$89,$f0,$01,$81,$6f,$01,$81,$7c,$01,$81
	.byte $8a,$01,$81,$97,$01,$81,$a5,$01,$81,$b2,$01,$81,$c0,$01,$81,$cd
	.byte $01,$81,$db,$01,$81,$e8,$01,$81,$f6,$01,$81,$03,$82,$01,$01,$81
	.byte $11,$01,$81,$1e,$01,$81,$2c,$01,$81,$39,$01,$81,$3f,$00
@sfx_ntsc_boom:
	.byte $8a,$0e,$89,$3f,$14,$8a,$0f,$0a,$8a,$0e,$06,$8a,$0f,$0c,$00
@sfx_ntsc_bigboom:
	.byte $89,$f0,$01,$8a,$0f,$89,$3f,$07,$8a,$0e,$08,$8a,$0d,$08,$8a,$0c
	.byte $08,$8a,$0b,$08,$8a,$0a,$12,$8a,$02,$03,$8a,$01,$04,$8a,$00,$04
	.byte $8a,$0f,$04,$8a,$0e,$04,$8a,$0d,$03,$00

.export sounds
